apiVersion: v1
kind: Service
metadata:
  name: rkllm-openai-server-service
  namespace: rkllm-openai
  labels:
    app: rkllm-openai-server
spec:
  selector:
    app: rkllm-openai-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
